[package]
name = "depman"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.0"
serde = { version = "1.0.217", features = ["derive"] }
simple-regex = "1.0.1"
tempfile = "3.15.0"
toml = "0.8.19"
util = { version = "0.1.0", path = "../util" }
