[package]
name = "cpppm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
cli = { version = "0.1.0", path = "../cli" }
util = { version = "0.1.0", path = "../util" }
